/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsaasRouteImport } from './routes/asaas'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ImportacaoRouteImport } from './routes/importacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as RecorrenciasRouteImport } from './routes/recorrencias'
import { Route as TransacoesRouteImport } from './routes/transacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsaasRoute = AsaasRouteImport.update({
  id: '/asaas',
  path: '/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacaoRoute = ImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorrenciasRoute = RecorrenciasRouteImport.update({
  id: '/recorrencias',
  path: '/recorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asaas': typeof AsaasRoute
  '/categorias': typeof CategoriasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/importacao': typeof ImportacaoRoute
  '/login': typeof LoginRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recorrencias': typeof RecorrenciasRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asaas': typeof AsaasRoute
  '/categorias': typeof CategoriasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/importacao': typeof ImportacaoRoute
  '/login': typeof LoginRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recorrencias': typeof RecorrenciasRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asaas': typeof AsaasRoute
  '/categorias': typeof CategoriasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/importacao': typeof ImportacaoRoute
  '/login': typeof LoginRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recorrencias': typeof RecorrenciasRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asaas'
    | '/categorias'
    | '/configuracoes'
    | '/contas'
    | '/importacao'
    | '/login'
    | '/planejamento'
    | '/recorrencias'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asaas'
    | '/categorias'
    | '/configuracoes'
    | '/contas'
    | '/importacao'
    | '/login'
    | '/planejamento'
    | '/recorrencias'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/asaas'
    | '/categorias'
    | '/configuracoes'
    | '/contas'
    | '/importacao'
    | '/login'
    | '/planejamento'
    | '/recorrencias'
    | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsaasRoute: typeof AsaasRoute
  CategoriasRoute: typeof CategoriasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  ImportacaoRoute: typeof ImportacaoRoute
  LoginRoute: typeof LoginRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  RecorrenciasRoute: typeof RecorrenciasRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asaas': {
      id: '/asaas'
      path: '/asaas'
      fullPath: '/asaas'
      preLoaderRoute: typeof AsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacao': {
      id: '/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof ImportacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorrencias': {
      id: '/recorrencias'
      path: '/recorrencias'
      fullPath: '/recorrencias'
      preLoaderRoute: typeof RecorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsaasRoute: AsaasRoute,
  CategoriasRoute: CategoriasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  ImportacaoRoute: ImportacaoRoute,
  LoginRoute: LoginRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  RecorrenciasRoute: RecorrenciasRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
